import './globals.css'
import type { Metadata } from 'next'
import LeftSidebar from './LeftSidebar'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen bg-background font-sans antialiased',
        'flex h-screen',
      )}
      >
        <LeftSidebar />
        {children}
      </body>
    </html>
  )
}
